const OPERATION_TYPES = Object.freeze({
  CREATE_SHAPE: "CREATE_SHAPE",
  UPDATE_SHAPE: "UPDATE_SHAPE",
  MOVE_SHAPE: "MOVE_SHAPE",
  DELETE_SHAPE: "DELETE_SHAPE",
  ROTATE_SHAPE: "ROTATE_SHAPE",
  RESIZE_SHAPE: "RESIZE_SHAPE",
  CHANGE_STYLE: "CHANGE_STYLE",
  BRING_FORWARD: "BRING_FORWARD",
  SEND_BACKWARD: "SEND_BACKWARD",
  GROUP: "GROUP",
  UNGROUP: "UNGROUP",
  UNDO: "UNDO",
  REDO: "REDO",
});

const SUPPORTED_OPERATION_TYPES = new Set(Object.values(OPERATION_TYPES));

module.exports = {
  OPERATION_TYPES,
  SUPPORTED_OPERATION_TYPES,
};
